# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a03c131dc734d8e5dba81004e8ca81e0cb533c519db44c9b10c9953e46d80835c62a84f36d25b9d07551a1df5998ccfa5328f25817492480b404356196cc7ae

test:
  secret_key_base: 3b00cda370e9afb86f6c0e1eda4e48e432eccd32b387c5e9f630ef7e96a9e6feeabbc0cd130ff10515eb9d2ff63ec2ff731a42293ddbbda1cc4a75500e370f51

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
